# Generated by Django 4.2.1 on 2023-05-08 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('salary', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(null=True, upload_to='Employee_photos/<django.db.models.fields.CharField>_<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(default='stub', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 2, 1, 33, 115003)),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='corporate_food.position'),
        ),
    ]
