# Generated by Django 4.2.1 on 2023-05-08 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_food', '0003_employee_time_end_work_employee_time_start_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time_end_work',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 2, 17, 35, 93954)),
        ),
    ]
