# Generated by Django 4.2.1 on 2023-05-08 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_food', '0004_alter_employee_time_end_work_alter_order_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 2, 17, 52, 416955)),
        ),
    ]
