# Generated by Django 4.2.1 on 2023-05-09 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_food', '0007_employee_time_end_work_alter_order_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 13, 31, 32, 215431)),
        ),
    ]
