# Generated by Django 4.2.1 on 2023-05-09 16:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_food', '0008_alter_order_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='edit_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_end_work',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_start_work',
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 22, 36, 2, 51705)),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start_work', models.TimeField(default=datetime.time(10, 0))),
                ('time_end_work', models.TimeField(default=datetime.time(19, 0))),
                ('day_work', models.DateField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corporate_food.employee')),
            ],
        ),
    ]
