# Generated by Django 4.2.1 on 2023-05-10 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_food', '0011_alter_order_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='difficult',
            field=models.CharField(choices=[('easy', 'Простое'), ('medium', 'Среднее'), ('hard', 'Сложное')], default='medium', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 16, 34, 40, 256489)),
        ),
    ]
