# Generated by Django 4.2.1 on 2023-05-10 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_food', '0012_dish_difficult_alter_order_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 16, 49, 57, 855494)),
        ),
    ]
