# Generated by Django 4.2.1 on 2023-05-10 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_food', '0013_remove_order_date_alter_order_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(null=True, upload_to='Dishes/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 18, 11, 17, 927896)),
        ),
    ]
